<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Lab3">
      <HintPath>..\..\..\..\Lab4\Lab3\Lab3\bin\Debug\net10.0-windows\Lab3.dll</HintPath>
    </Reference>
    <Reference Include="Lab3.Shared">
      <HintPath>..\..\Lab3.Shared\Lab3.Shared\bin\Debug\net10.0-windows\Lab3.Shared.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
